networks:
  task-tracker:
    driver: bridge

services:
  db:
    image: mysql:latest
    container_name: task-tracker_db
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: task_tracker
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./backend/db-data:/var/lib/mysql
    ports:
      - 4306:3306
    networks:
      - task-tracker
  
  test-db:
    image: mysql:latest
    container_name: task-tracker_test-db
    cap_add:
      - SYS_NICE
    command: --mysql-native-password=ON
    restart: always
    environment:
      MYSQL_DATABASE: task_tracker_test
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 2306:3306
    networks:
      - task-tracker
  
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: backend_image
    container_name: task-tracker_api
    depends_on:
      - db
    user: 1000:1000
    working_dir: /home/task-tracker
    ports:
      - 8848:8848
    volumes:
      - ./backend:/home/task-tracker
    networks:
      - task-tracker

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: frontend_image
    container_name: task-tracker_frontend
    depends_on:
      - backend
    user: 1000:1000
    working_dir: /home/task-tracker
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/home/task-tracker
    networks:
      - task-tracker
